name: Automatic Branch Merging

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  merge:
    name: Cascading Auto Merge
    runs-on: ubuntu-latest

    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'release/')

    steps:
      - name: Get GitHub App Token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM }}
          owner: ${{ github.repository_owner }}

      - name: Automatic Merge
        uses: ActionsDesk/cascading-downstream-merge@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefixes: release/
          ref_branch: development
          merge_token: ${{ steps.token.outputs.token }}
